### ISSUE TITLE
Falta etiqueta <caption> dentro del <table>

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2022-garbellotto-gazzera#4]
https://github.com/UCC-LabCompu2/proyecto2022-garbellotto-gazzera/blob/3152721317b1e737ce02452f956bf0c1b5f5e1cb/jugar-2.html#L38-L138

**Comment by fgazzera** [comment]
Hola profe! En nuestro caso no debemos colocarle un < caption > a nuestra tabla ya que esta funciona como el tablero del Sudoku.
Le muestro como quedaria con el < caption > pero si es necesario se lo dejamos puesto
![image](https://user-images.githubusercontent.com/101714990/173200163-47fce1d5-8944-48fa-8d14-010b4bcaf085.png)

**Comment by edme88** [comment]
dejenlo puesto... y si visualmente no les gusta, pueden quitarlo con un **CSS display: none**
Pero tiene que estar por temas de accesibilidad (y los programas que se emplean para leer pantallas)
